spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/music_stream_app}
      database: music_stream_app
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      # ⚠️ Thêm dòng này để tắt _class
      mapping:
        auto-index-creation: true
  main:
    allow-bean-definition-overriding: true

# Ẩn _class
spring.data.mongodb.mapping.type-key: null

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 86400000  # 24 hours in milliseconds
  refreshTokenExpiration: 604800000  # 7 days in milliseconds

# Logging Configuration
logging:
  level:
    iuh.fit.se.music_stream_app_backend: DEBUG
    org.springframework.data.mongodb: DEBUG
